name: profile-stack

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "config/stack.yml"

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gleich/profile_stack@master
        with:
          path: config/stack.yml
